import Link from 'next/link'

export default function TermsPage() {
  return (
    <div className="min-h-screen py-16 px-6">
      <div className="max-w-2xl mx-auto">
        <Link href="/login" className="text-blue-600 hover:underline text-sm mb-8 inline-block">
          &larr; back
        </Link>

        <h1 className="font-serif text-4xl mb-2">Terms of Service</h1>
        <p className="text-gray-500 text-sm mb-12">Last updated: April 2026</p>

        <div className="space-y-10 text-gray-700 leading-relaxed">

          <section>
            <h2 className="font-serif text-xl mb-3 text-black">What Compass is</h2>
            <p>Compass is a career guidance tool designed to help young Indians explore possible career directions. It uses psychometric questions and AI-generated analysis to suggest career paths. It is not a clinical psychological assessment, not a recruiting platform, and not a guarantee of any career outcome.</p>
          </section>

          <section>
            <h2 className="font-serif text-xl mb-3 text-black">AI-generated results</h2>
            <p>All psychometric scores, career path recommendations, and guidance chat responses on Compass are generated by artificial intelligence (Google Gemini). These results are <strong>indicative only</strong>. They reflect patterns in your responses and should be treated as a starting point for exploration, not as a definitive assessment of your abilities, personality, or potential.</p>
            <p className="mt-3">Compass makes no warranty, express or implied, that any recommendation will lead to employment, career success, or any other outcome. You are responsible for your own career decisions.</p>
          </section>

          <section>
            <h2 className="font-serif text-xl mb-3 text-black">Age requirement</h2>
            <p>You must be at least 16 years old to use Compass. By creating an account, you confirm that you meet this requirement. If we become aware that a user is under 16, we will delete their account and data.</p>
          </section>

          <section>
            <h2 className="font-serif text-xl mb-3 text-black">Your account</h2>
            <p>You are responsible for maintaining the security of your Google account used to sign in to Compass. Compass is not liable for any loss or damage resulting from unauthorised access to your account. You may not use Compass to impersonate another person or create multiple accounts to manipulate results.</p>
          </section>

          <section>
            <h2 className="font-serif text-xl mb-3 text-black">Acceptable use</h2>
            <p>You agree not to use Compass to:</p>
            <ul className="list-disc pl-6 mt-3 space-y-2">
              <li>Attempt to reverse engineer, scrape, or extract our AI prompts or question banks</li>
              <li>Submit false information to manipulate your results</li>
              <li>Use the platform in any way that violates applicable law</li>
              <li>Attempt to access other users' data</li>
            </ul>
          </section>

          <section>
            <h2 className="font-serif text-xl mb-3 text-black">Product changes</h2>
            <p>We reserve the right to modify, improve, or discontinue any part of Compass at any time. We may update these Terms and will note the date of the last change at the top of this page. Continued use of Compass after changes constitutes acceptance of the updated Terms.</p>
          </section>

          <section>
            <h2 className="font-serif text-xl mb-3 text-black">Limitation of liability</h2>
            <p>Compass is provided "as is" without warranties of any kind. To the maximum extent permitted by law, Compass and its creators shall not be liable for any indirect, incidental, or consequential damages arising from your use of the platform, including but not limited to career decisions made based on AI-generated recommendations.</p>
          </section>

          <section>
            <h2 className="font-serif text-xl mb-3 text-black">Governing law</h2>
            <p>These Terms are governed by and construed in accordance with the laws of India. Any disputes arising under these Terms shall be subject to the exclusive jurisdiction of the courts of India.</p>
          </section>

          <section>
            <h2 className="font-serif text-xl mb-3 text-black">Contact</h2>
            <p>For questions about these Terms, email <a href="mailto:mihird5554@gmail.com" className="text-blue-600 hover:underline">mihird5554@gmail.com</a>.</p>
          </section>

        </div>
      </div>
    </div>
  )
}
